security:
    # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory: { memory: ~ }
        fos_userbundle:
            id: fos_user.user_provider.username
        auth_token_user_provider:
            id: 'App\Security\AuthTokenUserProvider'
    provider: fos_userbundle
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512 #bcrypt
    role_hierarchy:
        ROLE_AUTEUR: ROLE_USER
        ROLE_ADMIN: ROLE_AUTEUR

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        apidoc:
            pattern: ^/[a-z]{2}/api/doc/
            security: false
        api:
            pattern: ^/[a-z]{2}/api/v[0-9]/
            stateless: true
            simple_preauth:
                authenticator: 'App\Security\AuthTokenAuthenticator'
            provider: auth_token_user_provider
            anonymous: ~
        main:
            pattern: ^/
            user_checker: security.user_checker
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
            logout:       true
            logout_on_user_change: true
            anonymous:    true
            remember_me:
                secret:   '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path:     /

            # activate different ways to authenticate

            # http_basic: true
            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: true
            # https://symfony.com/doc/current/security/form_login_setup.html

    # Easy way to control access for large sections of your site
    # Note: Only the *first* access control that matches will be used
    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }
