services:
    platform.antispam:
      class: PlatformBundle\Antispam\Antispam
      arguments:
        - "@mailer"
        - %locale%
        - 50

    # Emplacement spécifique pour des datafixtures
    # sinon, le chemin officiel pour stocker est src/DataFixtures/
    PlatformBundle\DataFixtures\ORM\LoadCategory:
      tags: ['doctrine.fixture.orm']

#    platform.example:
#        class: PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
