services:
    platform.antispam:
      class: PlatformBundle\Antispam\Antispam
      arguments:
        - "@mailer"
        - %locale%
        - 50

    # Emplacement spécifique pour des datafixtures
    # sinon, le chemin officiel pour stocker est src/DataFixtures/
    PlatformBundle\DataFixtures\ORM\LoadCategory:
      tags: ['doctrine.fixture.orm']

    PlatformBundle\DataFixtures\ORM\LoadSkill:
      tags: ['doctrine.fixture.orm']

#    platform.example:
#        class: PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    platform.service.application_mailer:
      class: PlatformBundle\Service\ApplicationMailer
      arguments:
          - "@mailer"

    platform.doctrine_listener.application_creation:
      class: PlatformBundle\DoctrineListener\ApplicationCreationListener
      arguments:
        - "@platform.service.application_mailer"
      tags:
        - { name: doctrine.event_listener, event: postPersist }

    platform.validator.antiflood:
      class: PlatformBundle\Validator\AntifloodValidator
      arguments: ["@request_stack", "@doctrine.orm.entity_manager"]
      tags:
        - { name: validator.constraint_validator, alias: platform_antiflood }
