services:
    platform.antispam:
      class: PlatformBundle\Antispam\Antispam
      arguments:
        - "@mailer"
        - %locale%
        - 50

#    platform.example:
#        class: PlatformBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
