version: '3'
services:
    traefik:
        container_name: ${DOCKER_APP_NAME}_traefik
        image: traefik
        command: -c /dev/null --api --docker --docker.domain=.docker --logLevel=DEBUG
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
          - /var/run/docker.sock:/var/run/docker.sock
        networks:
          - platform

networks:
    platform:
        external: true
