version: '3'
services:
    mysql:
        volumes:
            - ./var/data/docker-db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: ${DOCKER_APP_NAME}_phpmyadmin
        labels:
            traefik.enable: true
            traefik.http.port: 80
            traefik.http.frontend.rule: "Host: pma.docker"
            traefik.http.backend: "${DOCKER_APP_NAME}-phpmyadmin"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - "80"
        volumes:
          - ./config/docker/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php
        depends_on:
          - mysql
        links:
          - mysql
        networks:
          - platform

    maildev:
        image: djfarrelly/maildev
        container_name: ${DOCKER_APP_NAME}_maildev
        labels:
            traefik.enable: true
            traefik.http.port: 80
            traefik.http.frontend.rule: "Host: maildev.docker"
            traefik.http.frontend.frontend.passHostHeader: true
            traefik.http.backend: "${DOCKER_APP_NAME}-maildev"
        ports:
          - 80
          - "1025:25"
        networks:
          - platform

    traefik:
        container_name: ${DOCKER_APP_NAME}_traefik
        image: traefik
        command: -c /dev/null --api --docker --docker.domain=.docker --logLevel=DEBUG
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - platform

networks:
    platform:
        external: true
