version: '3.6'
services:
    mysql:
        build:
            context: config/docker/mysql
            args:
                MYSQL_USER: ${MYSQL_USER}
                MYSQL_PASSWORD: ${MYSQL_PASSWORD}
                MYSQL_PORT: ${MYSQL_PORT}
        volumes:
            - mysql-db:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        labels:
            traefik.enable: true
            traefik.http.port: 80
            traefik.http.frontend.rule: "Host: pma.docker"
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
            PMA_USER: ${MYSQL_USER}
            PMA_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - "80"
        volumes:
          - ./config/docker/phpmyadmin/config.inc.php:/etc/phpmyadmin/config.user.inc.php
        depends_on:
          - mysql
        links:
          - mysql
        networks:
          - platform

    maildev:
        image: djfarrelly/maildev
        labels:
            traefik.enable: true
            traefik.http.port: 80
            traefik.http.frontend.rule: "Host: maildev.docker"
            traefik.http.frontend.frontend.passHostHeader: true
        ports:
          - 80
          - "1025:25"
        networks:
          - platform

    traefik:
        image: traefik
        command: -c /dev/null --api --docker --docker.domain=.docker --logLevel=DEBUG
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - platform

networks:
    platform:
        external: true

volumes:
    mysql-db: #Keep database on local docker storage
