version: '3.6'
services:
    nginx:
        image: nginx
        labels:
            traefik.enable: true
            traefik.http.port: 80
            traefik.http.frontend.rule: "Host: platform.docker"
        ports:
          - "80"
          - "443"
        environment:
          - NGINX_HOST=platform.docker
        volumes:
          - .:/var/www
          - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./config/docker/nginx/symfony.conf:/etc/nginx/sites-enabled/symfony.conf
        restart: always
        depends_on:
          - php
          - mysql
        networks:
          - platform

    mysql:
        image: mysql:5.7
        command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - "3306:3306"
        networks:
          - platform

    php:
        build: config/docker/php
        restart: always
        volumes:
          - .:/var/www
          - ${COMPOSER_HOME:-/tmp/composer}:/home/www-data/.composer # Share composer cache
        ports:
          - "9010"
        depends_on:
          - mysql
        networks:
          - platform

networks:
    platform:
        driver: bridge
