version: '3'
services:
    nginx:
        image: nginx
        labels:
            traefik.enable: true
            traefik.http.port: 80
            traefik.http.frontend.rule: "Host: platform.docker"
        ports:
          - "80"
          - "443"
        environment:
          - NGINX_HOST=platform.docker
        volumes:
          - .:/var/www
          - ./config/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
          - ./config/docker/nginx/symfony.conf:/etc/nginx/sites-enabled/symfony.conf
        restart: always
        depends_on:
          - php
          - mysql
        networks:
          - platform

    mysql:
        image: mysql:5.7
        volumes:
          - ./var/data/docker-db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        ports:
          - "3306:3306"
        networks:
          - platform

    php:
        build: config/docker/php
        volumes:
          - .:/var/www
          - ${COMPOSER_HOME:-/tmp/composer}:/home/www-data/.composer # Share composer cache
        environment:
          - maildev_host=maildev.docker
        ports:
          - "9010"
        depends_on:
          - mysql
        networks:
          - platform

networks:
    platform:
        driver: bridge
