homepage:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: oc_platform_home
    permanent: true

platform:
  resource: "@PlatformBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/platform
  requirements:
    _locale: en|fr

user:
  resource: "@MyUserBundle/Resources/config/routing.yml"
  prefix:   /{_locale}
  requirements:
    _locale: en|fr

rest_api:
  resource: "@MyRestBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/api
  requirements:
    _locale: en|fr

# app/config/routing.yml
easy_admin_bundle:
  resource: "@EasyAdminBundle/Controller/AdminController.php"
  type:     annotation
  prefix:   /admin
