platform:
    resource: "@PlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

login:
  path: /login
  defaults:
    _controller: MyUserBundle:Security:login

login_check:
  path: /login_check

logout:
  path: /logout
