homepage:
  path: /
  defaults:
    _controller: FrameworkBundle:Redirect:redirect
    route: oc_platform_home
    permanent: true

platform:
  resource: "@PlatformBundle/Resources/config/routing.yml"
  prefix:   /{_locale}/platform
  requirements:
    _locale: en|fr

user:
  resource: "@MyUserBundle/Resources/config/routing.yml"
  prefix:   /{_locale}
  requirements:
    _locale: en|fr