# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    MyUserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       [ ROLE_AUTEUR, ROLE_MODERATEUR ]
    ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    myuserprovider:
      id: fos_user.user_provider.username

    auth_token_user_provider:
      id: auth_token_user_provider

  provider: myuserprovider
  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    apidoc:
      pattern: ^/[a-z]{2}/api/doc/
      security: false

    api:
      pattern: ^/[a-z]{2}/api/v[0-9]/
      stateless: true
      simple_preauth:
        authenticator: auth_token_authenticator
      provider: auth_token_user_provider
      anonymous: ~

    main:
      pattern: ^/
      anonymous: true
      provider: myuserprovider
      form_login:
        login_path: fos_user_security_login
        check_path: fos_user_security_check
      logout:
        path:       fos_user_security_logout
        target:     fos_user_security_login
      remember_me:
        secret:     '%secret%'

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    #- { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }


    # activate different ways to authenticate

    # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
    #http_basic: ~

    # https://symfony.com/doc/current/security/form_login_setup.html
    #form_login: ~


