# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
  encoders:
    MyUserBundle\Entity\User: sha512

  role_hierarchy:
    ROLE_ADMIN:       [ ROLE_AUTEUR, ROLE_MODERATEUR ]
    ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

  # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
  providers:
    myuserprovider:
      id: fos_user.user_provider.username

  provider: myuserprovider
  firewalls:
    # disables authentication for assets and the profiler, adapt it according to your needs
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      pattern: ^/
      anonymous: true
      provider: myuserprovider
      form_login:
        login_path: login
        check_path: login_check
      logout:
        path:       logout
        target:     login
      remember_me:
        secret:     %secret%

  access_control:
    - { path: ^/admin, roles: ROLE_ADMIN }
    #- { path: ^/admin, ip: 127.0.0.1, requires_channel: https }
    #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }


    # activate different ways to authenticate

    # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
    #http_basic: ~

    # https://symfony.com/doc/current/security/form_login_setup.html
    #form_login: ~


