<?php

namespace App\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AdvertSkillRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertSkillRepository extends EntityRepository
{
}
