advert_api:
    resource: "@MyRestBundle/Controller/ApiAdvertController.php"
    type:     rest
    prefix:   /v1

application_api:
    resource: "@MyRestBundle/Controller/ApiApplicationController.php"
    type:     rest
    prefix:   /v1
