# Specifics rules to add avert with API
PlatformBundle\Entity\Advert:
  constraints:
    - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: title
  properties:
    title:
      - NotBlank: ~
      - Type: string
    author:
      - NotBlank: ~
      - Type: string
    content:
      - NotBlank: ~
      - Type: string

PlatformBundle\Entity\Application:
  properties:
    author:
      - NotBlank: ~
      - Type: string
    content:
      - NotBlank: ~
      - Type: string
    city:
      - Choice: [Paris, Dunwall, Angoulême, Nice]
    salaryClaim:
      - GreaterThanOrEqual: 1500

# User Rest API Auth
MyRestBundle\Entity\Credentials:
  properties:
    login:
      - NotBlank: ~
      - Type: string
    password:
      - NotBlank: ~
      - Type: string
