services:
#    my_user.example:
#        class: OC\MyUserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    MyUserBundle\DataFixtures\ORM\LoadUser:
        tags: ['doctrine.fixture.orm']
